const BLE_SERVICE_UUID = "6E400001-B5A3-F393-E0A9-E50E24DCCA9E";
const BLE_CHARACTERISTIC_UUID = "6E400002-B5A3-F393-E0A9-E50E24DCCA9E";

const RSSI_THRESHOLDS = {
  IMMEDIATE: -40,
  NEAR: -55,
  MEDIUM: -70,
  FAR: -85,
  DEFAULT: -70,
};

const BROADCAST_PREFIX = "ATT";
const BROADCAST_VERSION = 1;

const SCAN_DURATION_MS = 10000;
const SCAN_INTERVAL_MS = 1000;

const BLE_STATE = {
  UNKNOWN: "Unknown",
  RESETTING: "Resetting",
  UNSUPPORTED: "Unsupported",
  UNAUTHORIZED: "Unauthorized",
  POWERED_OFF: "PoweredOff",
  POWERED_ON: "PoweredOn",
};

module.exports = {
  BLE_SERVICE_UUID,
  BLE_CHARACTERISTIC_UUID,
  RSSI_THRESHOLDS,
  BROADCAST_PREFIX,
  BROADCAST_VERSION,
  SCAN_DURATION_MS,
  SCAN_INTERVAL_MS,
  BLE_STATE,
};
