// attend_html.h — Attendance portal HTML served by the ESP32 captive portal.
// Kept in a separate header to avoid Arduino's sketch pre-preprocessor mangling
// multi-line string literals inside .ino files.

#pragma once

// Part 1: everything before the dynamic course/lecturer injection
static const char ATTEND_HTML_1[] =
"<!doctype html>"
"<html><head><meta charset='utf-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1,maximum-scale=1'>"
"<title>Mark Attendance</title>"
"<style>"
"*{box-sizing:border-box;margin:0;padding:0}"
"body{min-height:100vh;background:#0a0f1e;color:#fff;"
"font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;"
"display:flex;align-items:center;justify-content:center;padding:20px}"
".card{background:#111827;border-radius:20px;padding:28px 20px;"
"max-width:360px;width:100%;border:1px solid #1e2d45}"
".logo{text-align:center;font-size:22px;font-weight:900;color:#fff;margin-bottom:2px}"
".logo span{color:#4f6ef7}"
".dot{width:8px;height:8px;background:#22c55e;border-radius:50%;"
"display:inline-block;margin-right:5px;vertical-align:middle}"
".live{text-align:center;font-size:11px;color:#22c55e;margin-bottom:4px}"
".course{text-align:center;font-size:15px;font-weight:700;"
"color:#e2e8f0;margin:10px 0 2px}"
".lect{text-align:center;font-size:12px;color:#64748b;margin-bottom:20px}"
"label{display:block;font-size:11px;font-weight:600;color:#94a3b8;"
"text-transform:uppercase;letter-spacing:.5px;margin-bottom:6px}"
"input[type=text]{width:100%;padding:13px 14px;background:#0f172a;"
"border:1.5px solid #1e2d45;border-radius:10px;color:#fff;font-size:16px;"
"outline:none;margin-bottom:16px;-webkit-appearance:none}"
"input[type=text]:focus{border-color:#4f6ef7}"
".cr{display:flex;gap:7px;margin-bottom:22px}"
".cb{flex:1;padding:12px 0;background:#0f172a;border:1.5px solid #1e2d45;"
"border-radius:10px;color:#fff;font-size:22px;font-weight:700;"
"text-align:center;outline:none;-webkit-appearance:none;caret-color:#4f6ef7}"
".cb:focus{border-color:#4f6ef7}"
"button{width:100%;padding:15px;background:#4f6ef7;color:#fff;border:none;"
"border-radius:12px;font-size:15px;font-weight:700;cursor:pointer;"
"-webkit-tap-highlight-color:transparent}"
"button:disabled{opacity:.5}"
".err{display:none;background:#450a0a;border:1px solid #991b1b;border-radius:10px;"
"padding:12px 14px;color:#fca5a5;font-size:13px;margin-bottom:14px}"
".ok{display:none;text-align:center;padding:8px 0}"
".ck{font-size:60px;margin-bottom:14px}"
".ok h2{color:#22c55e;font-size:18px;margin-bottom:8px}"
".ok p{color:#64748b;font-size:13px;line-height:1.6}"
".tmr{text-align:center;font-size:11px;color:#475569;margin-top:14px}"
".closed{background:#1c1a10;border:1px solid #713f12;border-radius:10px;"
"padding:12px 14px;color:#fcd34d;font-size:13px;text-align:center;margin-top:4px}"
"</style></head>"
"<body><div class='card'>"
"<div class='logo'>Di<span>kly</span></div>"
"<div class='live'><span class='dot'></span>Session Active</div>";

// Part 2: everything after course/lecturer, before the endUnix injection
static const char ATTEND_HTML_2[] =
"<div id='err' class='err'></div>"
"<div id='main'>"
"<label>Index Number</label>"
"<input type='text' id='idx' placeholder='e.g. STU/2021/001'"
" autocomplete='off' autocorrect='off' spellcheck='false' autocapitalize='characters'>"
"<label>Attendance Code</label>"
"<div class='cr'>"
"<input class='cb' id='c0' maxlength='1' inputmode='numeric' pattern='[0-9]'>"
"<input class='cb' id='c1' maxlength='1' inputmode='numeric' pattern='[0-9]'>"
"<input class='cb' id='c2' maxlength='1' inputmode='numeric' pattern='[0-9]'>"
"<input class='cb' id='c3' maxlength='1' inputmode='numeric' pattern='[0-9]'>"
"<input class='cb' id='c4' maxlength='1' inputmode='numeric' pattern='[0-9]'>"
"<input class='cb' id='c5' maxlength='1' inputmode='numeric' pattern='[0-9]'>"
"</div>"
"<button id='btn' onclick='go()'>Mark Attendance</button>"
"<div class='tmr' id='tmr'></div>"
"</div>"
"<div class='ok' id='ok'>"
"<div class='ck'>&#x2705;</div>"
"<h2>Attendance Marked!</h2>"
"<p>You&#39;re checked in.<br>You can now disconnect from Dikly WiFi and use your normal network.</p>"
"</div>"
"</div>"
"<script>"
"var boxes=[0,1,2,3,4,5].map(function(i){return document.getElementById('c'+i);});"
"boxes.forEach(function(b,i){"
"b.addEventListener('input',function(){if(b.value&&i<5)boxes[i+1].focus();});"
"b.addEventListener('keydown',function(e){if(e.key==='Backspace'&&!b.value&&i>0){e.preventDefault();boxes[i-1].focus();}});"
"b.addEventListener('paste',function(e){"
"e.preventDefault();"
"var t=(e.clipboardData||window.clipboardData).getData('text').replace(/\\D/g,'').slice(0,6);"
"t.split('').forEach(function(c,j){if(boxes[i+j])boxes[i+j].value=c;});"
"var last=Math.min(i+t.length,5);boxes[last].focus();"
"});"
"});"
"function getCode(){return boxes.map(function(b){return b.value;}).join('');}"
"function go(){"
"var idx=document.getElementById('idx').value.trim().toUpperCase();"
"var code=getCode();"
"var err=document.getElementById('err');"
"err.style.display='none';"
"if(!idx){err.textContent='Please enter your index number.';err.style.display='block';return;}"
"if(code.length!==6){err.textContent='Enter all 6 digits of the attendance code.';err.style.display='block';return;}"
"var btn=document.getElementById('btn');"
"btn.textContent='Submitting\xe2\x80\xa6';btn.disabled=true;"
"fetch('/attend',{method:'POST',headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({indexNumber:idx,code:code})})"
".then(function(r){return r.json().then(function(d){return{ok:r.ok,d:d};});})"
".then(function(r){"
"if(r.ok){document.getElementById('main').style.display='none';document.getElementById('ok').style.display='block';}"
"else{err.textContent=r.d.error||'Something went wrong. Try again.';err.style.display='block';btn.textContent='Mark Attendance';btn.disabled=false;}"
"}).catch(function(){"
"err.textContent='Connection lost. Move closer to the device and try again.';"
"err.style.display='block';btn.textContent='Mark Attendance';btn.disabled=false;"
"});}"
"var endUnix=";  // endUnix value injected between part2 and part3

// Part 3: after endUnix injection
static const char ATTEND_HTML_3[] =
";"
"function tick(){"
"var s=Math.max(0,endUnix-Math.floor(Date.now()/1000));"
"var m=Math.floor(s/60),sc=s%60;"
"var el=document.getElementById('tmr');"
"if(s>0){el.textContent='Check-in closes in '+m+':'+(sc<10?'0':'')+sc;setTimeout(tick,1000);}"
"else{el.innerHTML='<div class=\"closed\">&#x26A0; Check-in window is closed</div>';}"
"}"
"tick();"
"document.getElementById('idx').focus();"
"</script></body></html>";
