import os, shutil
from PIL import Image

d_icon = Image.open('/tmp/dikly-icon.png').convert('RGBA')
print(f'Icon loaded: {d_icon.size}')

def make_icon(target_size):
    bg = Image.new('RGB', (target_size, target_size), (255, 255, 255))
    d = d_icon.resize((target_size, target_size), Image.LANCZOS)
    bg.paste(d, (0, 0), d.split()[3])
    return bg

for f in [
    'android/app/src/main/res/drawable/ic_launcher_foreground.xml',
    'android/app/src/main/res/drawable/ic_launcher_background.xml',
    'android/app/src/main/res/drawable-v24/ic_launcher_foreground.xml',
    'android/app/src/main/res/drawable-v24/ic_launcher_background.xml',
]:
    if os.path.exists(f):
        os.remove(f)

if os.path.exists('android/app/src/main/res/mipmap-anydpi-v26'):
    shutil.rmtree('android/app/src/main/res/mipmap-anydpi-v26')
    print('Removed adaptive icon folder')

for folder, size in [('mipmap-mdpi',48),('mipmap-hdpi',72),('mipmap-xhdpi',96),('mipmap-xxhdpi',144),('mipmap-xxxhdpi',192)]:
    out = f'android/app/src/main/res/{folder}'
    os.makedirs(out, exist_ok=True)
    ico = make_icon(size)
    ico.save(f'{out}/ic_launcher.png')
    ico.save(f'{out}/ic_launcher_round.png')
    print(f'  {folder}: {size}px')

# Android 12+ splash icon: transparent DIKLY logo, 288px (fits ≤160dp at xxxhdpi)
os.makedirs('android/app/src/main/res/drawable', exist_ok=True)
splash_icon = d_icon.resize((288, 288), Image.LANCZOS)
splash_icon.save('android/app/src/main/res/drawable/ic_splash.png')
print('ic_splash.png written (288px transparent, for Android 12+ splash)')

# Splash screen is now generated by gen_splash.py
import subprocess, sys
result = subprocess.run([sys.executable, 'scripts/gen_splash.py'], capture_output=True, text=True)
print(result.stdout)
if result.returncode != 0:
    print('Splash gen error:', result.stderr)
    # Fallback: plain branded splash
    splash = Image.new('RGB', (1080, 1920), (8, 15, 32))
    os.makedirs('android/app/src/main/res/drawable', exist_ok=True)
    splash.save('android/app/src/main/res/drawable/splash.png')
    print('Fallback splash saved.')
