"use strict";

/**
 * UserBadge.js
 *
 * Records a badge awarded to a specific user.
 *
 * Design decisions:
 *  - One document per (company, user, badge) pair.  A revoked badge keeps its
 *    document so the award history is preserved; a new award after revocation
 *    updates isRevoked back to false rather than creating a duplicate.
 *  - awardedBy = null means the award was auto-generated by the achievement
 *    check endpoint (system award).
 *
 * Tenant field: `company` (ObjectId).
 */

const mongoose = require("mongoose");

const userBadgeSchema = new mongoose.Schema(
  {
    // ── Tenant & context ──────────────────────────────────────────────────
    company: {
      type:     mongoose.Schema.Types.ObjectId,
      ref:      "Company",
      required: true,
      index:    true,
    },
    user: {
      type:     mongoose.Schema.Types.ObjectId,
      ref:      "User",
      required: true,
      index:    true,
    },
    badge: {
      type:     mongoose.Schema.Types.ObjectId,
      ref:      "Badge",
      required: true,
    },

    // ── Award metadata ────────────────────────────────────────────────────
    awardedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null }, // null = system
    awardedAt: { type: Date, default: Date.now },
    note:      { type: String, default: "", trim: true },     // optional message from awarder

    // ── Revocation ────────────────────────────────────────────────────────
    isRevoked:    { type: Boolean, default: false },
    revokedBy:    { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
    revokedAt:    { type: Date, default: null },
    revokeReason: { type: String, default: null },
  },
  { timestamps: true }
);

// ── Indexes ────────────────────────────────────────────────────────────────

// Unique: one award record per user per badge (revoked or not)
userBadgeSchema.index(
  { company: 1, user: 1, badge: 1 },
  { unique: true, name: "unique_user_badge" }
);
// All non-revoked awards for a user (profile page)
userBadgeSchema.index({ company: 1, user: 1, isRevoked: 1 });
// All awards for a badge (leaderboard / stats)
userBadgeSchema.index({ company: 1, badge: 1, isRevoked: 1 });

const UserBadge = mongoose.model("UserBadge", userBadgeSchema);
module.exports = UserBadge;
